-- ================================================================
-- King's Shalom - Supabase News Table Setup
-- Run this entire script in your Supabase SQL Editor
-- ================================================================

-- 1. Create the news table
create table if not exists public.news (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  category text not null,
  author text not null,
  date date not null,
  image_url text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

-- 2. Index for fast recent-news queries
create index if not exists news_created_at_idx
  on public.news (created_at desc);

-- 3. Enable Row Level Security
alter table public.news enable row level security;

-- 4. Allow public (anonymous) reads - so the website can fetch news without authentication
create policy "Allow public read access to news"
  on public.news
  for select
  to anon
  using (true);

-- 5. Allow service role full access (create, update, delete)
--    The service_role key is used by server.js and bypasses RLS automatically,
--    but we add an explicit policy for clarity.
create policy "Allow service role full access to news"
  on public.news
  for all
  to service_role
  using (true)
  with check (true);
