create table if not exists public.news (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  category text not null,
  author text not null,
  date date not null,
  image_url text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists news_created_at_idx
  on public.news (created_at desc);

alter table public.news enable row level security;
revoke all on table public.news from anon, authenticated;
